force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>APP - {0000}</displayFormat>
        <label>Application No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Application__c/fields/Requested_Loan_Amount__c.field-meta.xml
<CustomField>
    <fullName>Requested_Loan_Amount__c</fullName>
    <label>Requested Loan Amount</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Fee_Creation__c/Fee_Creation__c.object-meta.xml
<CustomObject>
    <label>Fee Creation</label>
    <nameField>
        <displayFormat>FC-{000000}</displayFormat>
        <label>Fee Creation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fee Creations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Fee_Creation__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Fee Creations</relationshipLabel>
    <relationshipName>Fee_Creations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Fee_Creation__c/fields/Fee_Code__c.field-meta.xml
<CustomField>
    <fullName>Fee_Code__c</fullName>
    <label>Fee Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>PRC_FEE_Type</fullName>
            </value>
            <value>
                <fullName>Cersai</fullName>
            </value>
            <value>
                <fullName>Technical</fullName>
            </value>
            <value>
                <fullName>LegaL</fullName>
            </value>
            <value>
                <fullName>IMD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Fee_Creation__c/fields/Fee_Type_Master__c.field-meta.xml
<CustomField>
    <fullName>Fee_Type_Master__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fee Code Master</label>
    <referenceTo>Fee_Type_Master__c</referenceTo>
    <relationshipLabel>Fee Creations</relationshipLabel>
    <relationshipName>Fee_Creations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Fee_Creation__c/fields/Premium__c.field-meta.xml
<CustomField>
    <fullName>Premium__c</fullName>
    <label>Premium</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Fee_Creation__c/fields/Repayment_Type_2__c.field-meta.xml
<CustomField>
    <fullName>Repayment_Type_2__c</fullName>
    <label>Repayment Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Direct Receipt</fullName>
            </value>
            <value>
                <fullName>Deduct from Disbursement</fullName>
            </value>
            <value>
                <fullName>Add to Loan Amount</fullName>
                <isActive>false</isActive>
                <label>Add to Loan Amount</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Fee_Creation__c/fields/Stage_Due__c.field-meta.xml
<CustomField>
    <fullName>Stage_Due__c</fullName>
    <label>Stage Due,</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pre Login</fullName>
            </value>
            <value>
                <fullName>Disbursement</fullName>
            </value>
            <value>
                <fullName>Pre Disbursement</fullName>
            </value>
            <value>
                <fullName>Post Disbursement</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Fee_Creation__c/fields/Sum_Assured__c.field-meta.xml
<CustomField>
    <fullName>Sum_Assured__c</fullName>
    <label>Sum Assured</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Fee_Creation__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>System</fullName>
            </value>
            <value>
                <fullName>User</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Fee_Creation__c/recordTypes/Fee.recordType-meta.xml
<RecordType>
    <fullName>Fee</fullName>
    <active>true</active>
    <label>Fee</label>
</RecordType>

force-app/main/default/objects/Fee_Creation__c/recordTypes/Insurance.recordType-meta.xml
<RecordType>
    <fullName>Insurance</fullName>
    <active>true</active>
    <label>Insurance</label>
</RecordType>

force-app/main/default/objects/Fee_Type_Master__c/Fee_Type_Master__c.object-meta.xml
<CustomObject>
    <label>Fee Type Master</label>
    <nameField>
        <label>Fee Type Master Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fee Type Masters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Fee_Type_Master__c/fields/Fee_Type__c.field-meta.xml
<CustomField>
    <fullName>Fee_Type__c</fullName>
    <label>Fee Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>System</fullName>
            </value>
            <value>
                <fullName>User</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Fee_Type_Master__c/fields/Fee_Type_Code__c.field-meta.xml
<CustomField>
    <fullName>Fee_Type_Code__c</fullName>
    <label>Fee Type Code</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>PRC_FEE_Type</fullName>
            </value>
            <value>
                <fullName>Cersai</fullName>
            </value>
            <value>
                <fullName>Technical</fullName>
            </value>
            <value>
                <fullName>LegaL</fullName>
            </value>
            <value>
                <fullName>IMD</fullName>
            </value>
            <value>
                <fullName>Ins-PRC_FEE_Type</fullName>
            </value>
            <value>
                <fullName>Ins-Cersai</fullName>
            </value>
            <value>
                <fullName>Ins-Technical</fullName>
            </value>
            <value>
                <fullName>Ins-LegaL</fullName>
            </value>
            <value>
                <fullName>Ins-IMD</fullName>
            </value>
            <value>
                <fullName>Usr-PRC_FEE_Type</fullName>
            </value>
            <value>
                <fullName>Usr-Cersai</fullName>
            </value>
            <value>
                <fullName>Usr-Technical</fullName>
            </value>
            <value>
                <fullName>Usr-LegaL</fullName>
            </value>
            <value>
                <fullName>Usr-IMD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Fee_Type_Master__c/fields/Repayment_of_Fee__c.field-meta.xml
<CustomField>
    <fullName>Repayment_of_Fee__c</fullName>
    <label>Repayment of Fee</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Direct Receipt</fullName>
            </value>
            <value>
                <fullName>Deduct from Disbursement</fullName>
            </value>
            <value>
                <fullName>Add to Loan Amount</fullName>
                <isActive>false</isActive>
                <label>Add to Loan Amount</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Fee_Type_Master__c/fields/Stage_Due__c.field-meta.xml
<CustomField>
    <fullName>Stage_Due__c</fullName>
    <label>Stage Due</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pre Login</fullName>
            </value>
            <value>
                <fullName>Disbursement</fullName>
            </value>
            <value>
                <fullName>Pre Disbursement</fullName>
            </value>
            <value>
                <fullName>Post Disbursement</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Fee_Type_Master__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fee</fullName>
            </value>
            <value>
                <fullName>Insurance</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Fee_Value_Master__c/Fee_Value_Master__c.object-meta.xml
<CustomObject>
    <label>Fee Value Master</label>
    <nameField>
        <displayFormat>FVM-{0000}</displayFormat>
        <label>Fee Value Master Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fee Value Master</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Fee_Value_Master__c/fields/Fee_Type__c.field-meta.xml
<CustomField>
    <fullName>Fee_Type__c</fullName>
    <formula>TEXT( Fee_Type_Master__r.Fee_Type__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Fee Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Fee_Value_Master__c/fields/Fee_Type_Code__c.field-meta.xml
<CustomField>
    <fullName>Fee_Type_Code__c</fullName>
    <formula>TEXT(Fee_Type_Master__r.Fee_Type_Code__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Fee Type Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Fee_Value_Master__c/fields/Fee_Type_Master__c.field-meta.xml
<CustomField>
    <fullName>Fee_Type_Master__c</fullName>
    <label>Fee Type Master</label>
    <referenceTo>Fee_Type_Master__c</referenceTo>
    <relationshipLabel>Fee Value Master</relationshipLabel>
    <relationshipName>Fee_Value_Master</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/FeeCreationTypeInsuranceNewController.cls
/**
* @Class Name         : FeeCreationTypeInsuranceNewController.apxc
* @Description        : Class to fetch details from Fee_Creation__c, Fee_Type_Master__c and Fee_Value_Master__c for insurance child component
						on Pre-Login Screen/Fee Details.
* @Author             : Sangeeta Yadv
* @Created On         : 25/07/2022
*========================================================================================
* Ver         Date                     Author                       Modification
*========================================================================================
* 1.0      25/07/2022               Sangeeta Yadav                  Initial Version
**/
public with sharing class FeeCreationTypeInsuranceNewController {

    /*
    @Author : Sangeeta
    @Description : This method is used to fetch fee creation records for given application id.
    */
    @AuraEnabled(cacheable = true)
    public static List<Fee_Creation__c> getFeeTypeInsurance(String applicationId){
        List<Fee_Creation__c> listOfExistingInsFeeCreation = new List<Fee_Creation__c>();
        try {
            if(String.isNotBlank(applicationId)){
                // Get fee creation records of type system and record type insurance with limit 1 to show only one record on UI
                listOfExistingInsFeeCreation = [SELECT Id,Type__c,Fee_Code__c,Stage_Due__c,Premium__c,Tax_Amount__c,
                                  Total_Fee__c,Sum_Assured__c,Repayment_Type_2__c, Application__r.Requested_Loan_Amount__c
                                  FROM Fee_Creation__c WHERE Application__c =: applicationId AND Type__c = 'System' AND RecordType.DeveloperName = 'Insurance' WITH SECURITY_ENFORCED];   
            }
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
        return listOfExistingInsFeeCreation;
    }

    /* 
    @Author : Sangeeta
    @Description : This method is used to creat fee creation record for given application id if it does not already contains fee creation records
                      based on fee type master records of type insurance and return single record to display on UI.
    */
    @AuraEnabled(cacheable = true)
    public static List<Fee_Creation__c> createFeeCreationInsuranceRecords (String applicationId){
        System.debug('@@## applicationId   '+applicationId);
        List<Fee_Creation__c> createFeeCreationInsuranceList = new List<Fee_Creation__c>();
        // Map of repayment and fee creation id for Repayment multi picklist from Fee_Type_Master__c object to pass to Rrpayment_Type_2__c picklist of Fee creation
        Map<String, String> mapFeeToRepayment = new Map<String,String>(); 
        // Map for fee creation Id and fee value master id for calculation
        Map<String, String> mapFeeToRepaymentmapFeeToValueMaster = new Map<String,String>(); 
        // fetch fee value of type system
        List<Fee_Value_Master__c> feeValueMasterList = [SELECT Id, Fee_Type_Code__c, Fee_Type__c, Description__c, Fee_Type_Master__r.Stage_Due__c, Fee_Type_Master__r.Repayment_of_Fee__c, Fee_Type_Master__r.Type__c FROM Fee_Value_Master__c WHERE Fee_Type__c = 'System' AND Fee_Type_Master__r.Type__c = 'Insurance'];
        // map to store existing records of type insurancefor given application 
        Map<String,Fee_Creation__c> existingFeeCreationInsuranceMap = new Map<String,Fee_Creation__c>();
		List<Fee_Creation__c> feeCreationInsList = [SELECT Id,Application__c,Application__r.Requested_Loan_Amount__c,Fee_Code__c, RecordType.Name FROM Fee_Creation__c WHERE Application__c =: applicationId AND RecordType.DeveloperName = 'Insurance'];
        for(Fee_Creation__c feeCreationIns : feeCreationInsList) {
            if(feeCreationIns.Application__c != null && feeCreationIns.Fee_Code__c != null && feeCreationIns.RecordType.Name == 'Insurance') {
                existingFeeCreationInsuranceMap.put(feeCreationIns.Application__c + '-' +feeCreationIns.Fee_Code__c, feeCreationIns );
            }
        }
        System.debug('EXISTING MAPPPPP   '+existingFeeCreationInsuranceMap);
        Decimal reqLoanAmount = [SELECT Id, Requested_Loan_Amount__c From Application__c WHERE Id =:applicationId].Requested_Loan_Amount__c;
        if(!feeValueMasterList.isEmpty()) {
            // create fee creation records based on master records
            for(Fee_Value_Master__c  feeValue : feeValueMasterList) {
                //System.debug('VALUEEEEE   '+ existingFeeCreationInsuranceMap.get(applicationId + '-' + feeValue.Fee_Type_Code__c));
                System.debug('Type   '+ feeValue.Fee_Type__c);
                System.debug('CODEEEEE   '+ feeValue.Fee_Type_Code__c);

                if(!(existingFeeCreationInsuranceMap.containsKey(applicationId + '-' + feeValue.Fee_Type_Code__c)) && String.IsNotBlank(feeValue.Fee_Type__c) && feeValue.Fee_Type__c == 'System') {
                    Fee_Creation__c feeCreation = new Fee_Creation__c();
                    feeCreation.Application__c = applicationId;
                    feeCreation.Fee_Code__c = feeValue.Fee_Type_Code__c;
                    feeCreation.Type__c = feeValue.Fee_Type__c;
                    feeCreation.Description__c = feeValue.Description__c;
                    feeCreation.Stage_Due__c = feeValue.Fee_Type_Master__r.Stage_Due__c;
                    feeCreation.Repayment_Type_2__c = 'Deduct from Disbursement';
                    //feeCreation.Sum_Assured__c = feeCreationInsList.Application__r.Requested_Loan_Amount__c;
                    // fetch record type Id for insurance to create records for insurance.
                    if(reqLoanAmount != null){
                        feeCreation.Sum_Assured__c = reqLoanAmount;}
                    else{feeCreation.Sum_Assured__c = 0;}
                    feeCreation.RecordTypeId = Schema.SObjectType.Fee_Creation__c.getRecordTypeInfosByDeveloperName().get('Insurance').getRecordTypeId();
                    createFeeCreationInsuranceList.add(feeCreation);
                }
            }
            System.debug('SIZEEEEEEEEEEEE   CREATE LIST  '+ createFeeCreationInsuranceList);
            if(!createFeeCreationInsuranceList.isEmpty()) {
                createFeeCreationRecord( JSON.serialize(createFeeCreationInsuranceList) );                
            }
        }
        return createFeeCreationInsuranceList;
    }

    /*
    @Author : Sangeeta
    @Description : This method is used to insert new created records as method called in lwc can not insert records directly  
    */
    @AuraEnabled(cacheable = true)
    @future
    public static void createFeeCreationRecord (String feeCreation)  {
        System.debug('feeCreation ' +feeCreation);
        if(String.isNotBlank(feeCreation)){
            List<Fee_Creation__c> feeCreationList = (List<Fee_Creation__c>)JSON.deserialize(feeCreation,List<Fee_Creation__c>.class);
            System.debug('VVVVVVVVVVVv ' +feeCreationList);
            insert feeCreationList;
        }
    }

    /*
    @Author : Sangeeta
    @Description : This method is used to update user entered sum insured on value change in sum insured column
    */
    @AuraEnabled(cacheable = true)
    Public static String updateFeeCreationInsuranceRecordsSumAssured(String feeCreationId, Decimal sumAssured, Decimal premium, Decimal taxAmount, Decimal totalFee, String repayment){
        system.debug('update fee creation' + feeCreationId + sumAssured);
        Fee_Creation__c feeCreationUpdate = [SELECT Id, Sum_Assured__c, Premium__c,Repayment_Type_2__c From Fee_Creation__c WHERE Id =: feeCreationId LIMIT 1];// limit to be add
        system.debug(feeCreationUpdate);
        feeCreationUpdate.Sum_Assured__c = sumAssured;
        feeCreationUpdate.Premium__c = premium;
        feeCreationUpdate.Tax_Amount__c = taxAmount;
        feeCreationUpdate.Total_Fee__c = totalFee;
        feeCreationUpdate.Repayment_Type_2__c = repayment;
        system.debug(feeCreationUpdate);
        if(feeCreationUpdate != null) {
            updateCallFeeCreationRecord( JSON.serialize(feeCreationUpdate) );
        }
        
        return 'feeCreationUpdate';
        
    }

    @AuraEnabled(cacheable=true)
    @future
    public static void updateCallFeeCreationRecord (String feeCreation)  {
        System.debug('update feecreation '+ feeCreation);
        Fee_Creation__c feeCreationUpdate = (Fee_Creation__c)JSON.deserialize(feeCreation,Fee_Creation__c.class);
        update(feeCreationUpdate);
        
    }

    /*
    @Author : Sangeeta
    @Description : To get picklist values based on fee value master.
    */
    @AuraEnabled(cacheable = true)
    public static Map<String, String> getRepaymentPicklist(String feeCode) {
        Map<String, String> values = new Map<String, String>{};
        if(String.isNotBlank(feeCode)){
            List<Fee_Type_Master__c> listOfFeeTypeMaster = [SELECT Id, Fee_Type_Code__c, Repayment_of_Fee__c FROM Fee_Type_Master__c
                                                        WHERE Fee_Type_Code__c =: feeCode];
            system.debug('listOfFeeTypeMaster '+ listOfFeeTypeMaster);
            if(listOfFeeTypeMaster != null && listOfFeeTypeMaster.size() > 0){
                List<String> repaymentList = new List<String>();
                if(String.IsNotBlank(listOfFeeTypeMaster[0].Repayment_of_Fee__c)){
                    if(listOfFeeTypeMaster[0].Repayment_of_Fee__c.contains(';')){
                        repaymentList = listOfFeeTypeMaster[0].Repayment_of_Fee__c.split(';');
                    }else{
                        repaymentList.add(listOfFeeTypeMaster[0].Repayment_of_Fee__c);
                    }
                }
                system.debug('repaymentList '+repaymentList);
                String objectName = 'Fee_Creation__c';
                String fieldName = 'Repayment_Type_2__c';
                
                List<Schema.DescribeSobjectResult> results = Schema.describeSObjects(new List<String>{objectName});
                String feeValue = '';
                for(Schema.DescribeSobjectResult res : results) {
                    for (Schema.PicklistEntry entry : res.fields.getMap().get(fieldName).getDescribe().getPicklistValues()) {
                        if (entry.isActive()) {
                            feeValue = entry.getLabel();
                            if(repaymentList.contains(feeValue)){
                                values.put(entry.getValue(), entry.getLabel());
                            }
                            system.debug('entry'+ feeValue);
                        }
                    }system.debug('map'+ values);
                }
            }
        }
        return values;
    }
    
    /*
@Author : Navin Soni
@Description : This method is use to call Kotak Calculate API.
*/
    /*  @AuraEnabled
public static List<Premium_Details__c> callKotakCalculateAPI(String applicationId){
KotakCalculateAPI.callKotakCalculateAPI(applicationId);
List<Premium_Details__c> listOfPremiumDetails = [SELECT Id, Application__c, Sum_Assured__c, Premium__c, Service_Tax__c, Total_Premium__c FROM Premium_Details__c where Application__c =: applicationId ORDER BY ID DESC LIMIT 1 ];
if(listOfPremiumDetails != null && listOfPremiumDetails.size() > 0){
return listOfPremiumDetails;
}
return null;
}*/


}