force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>APP - {0000}</displayFormat>
        <label>Application No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MS_Deviation__c/MS_Deviation__c.object-meta.xml
<CustomObject>
    <description>Deviation Master Object</description>
    <label>MS Deviation</label>
    <nameField>
        <displayFormat>DEV-{00000}</displayFormat>
        <label>MS Deviation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MS Deviations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MS_Deviation__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Code</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/MS_Deviation__c/fields/Deviation_Description__c.field-meta.xml
<CustomField>
    <fullName>Deviation_Description__c</fullName>
    <label>Deviation Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/MS_Deviation__c/fields/Deviation_Level__c.field-meta.xml
<CustomField>
    <fullName>Deviation_Level__c</fullName>
    <label>Deviation Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Application</fullName>
            </value>
            <value>
                <fullName>Applicant</fullName>
            </value>
            <value>
                <fullName>Asset</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MS_Deviation__c/fields/Deviation_Type__c.field-meta.xml
<CustomField>
    <fullName>Deviation_Type__c</fullName>
    <label>Deviation Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>System</fullName>
            </value>
            <value>
                <fullName>Manual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/pcDeviationController.cls
public class pcDeviationController {

    // to get the Deviation Table Records 
    @AuraEnabled
    public static GenericDataTableController.DataTableResponse getDeviationData(String appId ,String deviationType){
        
        GenericDataTableController genericDTObjCapabilty = new GenericDataTableController();
        genericDTObjCapabilty.METADATA_NAME = 'PC_Deviation_Grid' ;
        genericDTObjCapabilty.IDS_SET = new Set<String>();
        genericDTObjCapabilty.IDS_SET.add(appId);
        genericDTObjCapabilty.IDS_SET.add(deviationType);
        genericDTObjCapabilty.WHERE_CLAUSE =' Application__c IN : IDS_SET AND Deviation_Type__c IN :IDS_SET';
        return genericDTObjCapabilty.getTable();
    } 


    // to get all the codes from the MS Deviation Master to autopopulate in fields
    @AuraEnabled
    public static Map<String,MS_Deviation__c> getcodesfromDeviation()
    {

        Map<String,MS_Deviation__c> msMap = new Map<String,MS_Deviation__c>();
        for(MS_Deviation__c msObj:[SELECT Id,Code__c,Deviation_Description__c,Deviation_Level__c,Deviation_Type__c FROM MS_Deviation__c
        WHERE Deviation_Type__c = 'Manual'])
        {
            if(msObj.Code__c != null)
            msMap.put(msObj.Code__c,msObj);
        }
            return msMap;
    }

    
 


}